name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    services:
      devnet:
        image: shardlabs/starknet-devnet:0.5.1-seed0
        ports:
          - 5050:5050
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node version
        uses: actions/setup-node@v1
        with:
          node-version: 19.4.0
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Install pnpm
        run: |
          npm install -g pnpm
      - name: Print project structure
        run: |
          ls -R
      - name: Run build
        run: pnpm build
      - name: Run test
        run: pnpm test
