name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    services:
      devnet:
        image: shardlabs/starknet-devnet-rs:1bd447d8ac8c2fb0a3eaf2d54512671f4a16c7ba-seed0
        ports:
          - 5050:5050
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node version
        uses: actions/setup-node@v1
        with:
          node-version: 19.4.0
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.1.7
      - name: Install dependencies
        run: pnpm install --strict-peer-dependencies=false --no-frozen-lockfile
      - name: Print project structure
        run: |
          ls -R
      - name: Run build
        run: pnpm build
      - name: Run test
        run: pnpm test
